/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellAlertsRouteImport } from './routes/_shell/alerts'
import { Route as ShellBatteryHealthRouteImport } from './routes/_shell/battery-health'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellFaultDetectionRouteImport } from './routes/_shell/fault-detection'
import { Route as ShellLiveMonitoringRouteImport } from './routes/_shell/live-monitoring'
import { Route as ShellServiceRouteImport } from './routes/_shell/service'
import { Route as ShellTechnicianRouteImport } from './routes/_shell/technician'
import { Route as ShellTrendsRouteImport } from './routes/_shell/trends'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAlertsRoute = ShellAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBatteryHealthRoute = ShellBatteryHealthRouteImport.update({
  id: '/battery-health',
  path: '/battery-health',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFaultDetectionRoute = ShellFaultDetectionRouteImport.update({
  id: '/fault-detection',
  path: '/fault-detection',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLiveMonitoringRoute = ShellLiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => ShellRoute,
} as any)
const ShellServiceRoute = ShellServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTechnicianRoute = ShellTechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTrendsRoute = ShellTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof ShellAlertsRoute
  '/battery-health': typeof ShellBatteryHealthRoute
  '/dashboard': typeof ShellDashboardRoute
  '/fault-detection': typeof ShellFaultDetectionRoute
  '/live-monitoring': typeof ShellLiveMonitoringRoute
  '/service': typeof ShellServiceRoute
  '/technician': typeof ShellTechnicianRoute
  '/trends': typeof ShellTrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof ShellAlertsRoute
  '/battery-health': typeof ShellBatteryHealthRoute
  '/dashboard': typeof ShellDashboardRoute
  '/fault-detection': typeof ShellFaultDetectionRoute
  '/live-monitoring': typeof ShellLiveMonitoringRoute
  '/service': typeof ShellServiceRoute
  '/technician': typeof ShellTechnicianRoute
  '/trends': typeof ShellTrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/alerts': typeof ShellAlertsRoute
  '/_shell/battery-health': typeof ShellBatteryHealthRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/fault-detection': typeof ShellFaultDetectionRoute
  '/_shell/live-monitoring': typeof ShellLiveMonitoringRoute
  '/_shell/service': typeof ShellServiceRoute
  '/_shell/technician': typeof ShellTechnicianRoute
  '/_shell/trends': typeof ShellTrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/battery-health'
    | '/dashboard'
    | '/fault-detection'
    | '/live-monitoring'
    | '/service'
    | '/technician'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/battery-health'
    | '/dashboard'
    | '/fault-detection'
    | '/live-monitoring'
    | '/service'
    | '/technician'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/_shell/alerts'
    | '/_shell/battery-health'
    | '/_shell/dashboard'
    | '/_shell/fault-detection'
    | '/_shell/live-monitoring'
    | '/_shell/service'
    | '/_shell/technician'
    | '/_shell/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/alerts': {
      id: '/_shell/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof ShellAlertsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/battery-health': {
      id: '/_shell/battery-health'
      path: '/battery-health'
      fullPath: '/battery-health'
      preLoaderRoute: typeof ShellBatteryHealthRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/fault-detection': {
      id: '/_shell/fault-detection'
      path: '/fault-detection'
      fullPath: '/fault-detection'
      preLoaderRoute: typeof ShellFaultDetectionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/live-monitoring': {
      id: '/_shell/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof ShellLiveMonitoringRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/service': {
      id: '/_shell/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ShellServiceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/technician': {
      id: '/_shell/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof ShellTechnicianRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trends': {
      id: '/_shell/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof ShellTrendsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAlertsRoute: typeof ShellAlertsRoute
  ShellBatteryHealthRoute: typeof ShellBatteryHealthRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFaultDetectionRoute: typeof ShellFaultDetectionRoute
  ShellLiveMonitoringRoute: typeof ShellLiveMonitoringRoute
  ShellServiceRoute: typeof ShellServiceRoute
  ShellTechnicianRoute: typeof ShellTechnicianRoute
  ShellTrendsRoute: typeof ShellTrendsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAlertsRoute: ShellAlertsRoute,
  ShellBatteryHealthRoute: ShellBatteryHealthRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFaultDetectionRoute: ShellFaultDetectionRoute,
  ShellLiveMonitoringRoute: ShellLiveMonitoringRoute,
  ShellServiceRoute: ShellServiceRoute,
  ShellTechnicianRoute: ShellTechnicianRoute,
  ShellTrendsRoute: ShellTrendsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
